<a href="https://colab.research.google.com/github/anna-alt/AI-Lab/blob/main/SceneRecognition1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, SubsetRandomSampler, ConcatDataset
from torchvision import datasets, transforms
from torchvision import models

import numpy as np
import sklearn



In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

device

device(type='cuda')

In [3]:
trainset_size = 5000
val_size = 500
num_epochs = 10
image_size = (224,224)


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Resize(image_size),
                              
                              ])
# Download and load the training data
trainset = datasets.SUN397('/content/drive/MyDrive/Data', download= False, transform=transform)
splittrain = torch.utils.data.random_split(trainset, [trainset_size, len(trainset) - trainset_size])[0]
train_loader = DataLoader(splittrain, batch_size=32,num_workers = 2, shuffle=True)

validationset = datasets.SUN397("/content/drive/MyDrive/Data", download=False, transform=transform)
splitvalidation = torch.utils.data.random_split(validationset, [val_size, len(trainset) - val_size])[0]
val_loader = DataLoader(splitvalidation, batch_size=32,num_workers = 2, shuffle=True)



In [ ]:
for image, label in train_loader:
  labels = np.array(image)
  numpy_labels = label.numpy()
  print(labels)
  break


In [ ]:
model = models.resnet50(weights = "DEFAULT")
model.to(device)

In [ ]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, betas=(0.9, 0.999), eps=1e-8)
criterion = nn.CrossEntropyLoss()
print(model)

In [8]:
def train(epoch, log_interval=20):
    # Set model to training mode
    model.train()
    
    # Loop over each batch from the training set
    for batch_idx, (data, target) in enumerate(train_loader):
        # Copy data to GPU if needed
        data = data.to(device)
        target = target.to(device)

        # Zero gradient buffers
        optimizer.zero_grad() 
        
        # Pass data through the network
        output = model(data)

        # Calculate loss
        loss = criterion(output, target)

        # Backpropagate
        loss.backward()
        
        # Update weights
        optimizer.step()
        
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.data.item()))

In [9]:

def validate(loss_vector, accuracy_vector):
    model.eval()
    val_loss, correct = 0, 0
    for data, target in val_loader:
        data = data.to(device)
        target = target.to(device)
        output = model(data)
        val_loss += criterion(output, target).data.item()
        pred = output.data.max(1)[1] # get the index of the max log-probability
        correct += pred.eq(target.data).cpu().sum()

    val_loss /= len(val_loader)
    loss_vector.append(val_loss)

    print(pred)

    accuracy = 100. * correct.to(torch.float32) / len(val_loader.dataset)
    accuracy_vector.append(accuracy)

    
    print('\nValidation set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        val_loss, correct, len(val_loader.dataset), accuracy))

In [10]:
def Predic(loss_vector,accuracy_vector):
    val_loss, correct = 0, 0
    for data, target in val_loader:
        data = data.to(device)
        target = target.to(device)
        output = model(data)
        val_loss += criterion(output, target).data.item()
        pred = output.data.max(1)[1] # get the index of the max log-probability
        correct += pred.eq(target.data).cpu().sum()
    print( pred)
    print("/n")
    print(target)


In [11]:
lossv, accv = [], []
for epoch in range(1, num_epochs + 1):
    train(epoch)
    validate(lossv, accv)
    Predic(lossv,accv)

Train Epoch: 1 [0/5000 (0%)]	Loss: 7.627412
Train Epoch: 1 [640/5000 (13%)]	Loss: 6.729174
Train Epoch: 1 [1280/5000 (25%)]	Loss: 6.642689
Train Epoch: 1 [1920/5000 (38%)]	Loss: 5.491829
Train Epoch: 1 [2560/5000 (51%)]	Loss: 5.561943
Train Epoch: 1 [3200/5000 (64%)]	Loss: 5.538623


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 1 [3840/5000 (76%)]	Loss: 5.552651
Train Epoch: 1 [4480/5000 (89%)]	Loss: 4.719298
tensor([ 46,   2, 193, 133,  63,   2,  24, 234, 193, 376, 227, 338, 264, 892,
        245,  60, 300,   2, 184,  85], device='cuda:0')

Validation set: Average loss: 4.6550, Accuracy: 97/500 (19%)

tensor([370,  46, 245,  82, 300, 213, 227, 245, 213,  46,  60, 118,  75, 245,
        174, 234, 279, 335,   2, 937], device='cuda:0')
/n
tensor([284,  46, 245,  77, 208, 131,  58,  46, 213,  52,  60, 117, 391, 256,
         52, 106,  53,   6, 145,  57], device='cuda:0')
Train Epoch: 2 [0/5000 (0%)]	Loss: 3.725392
Train Epoch: 2 [640/5000 (13%)]	Loss: 3.766303
Train Epoch: 2 [1280/5000 (25%)]	Loss: 3.606399
Train Epoch: 2 [1920/5000 (38%)]	Loss: 3.531874
Train Epoch: 2 [2560/5000 (51%)]	Loss: 3.267872
Train Epoch: 2 [3200/5000 (64%)]	Loss: 3.587355
Train Epoch: 2 [3840/5000 (76%)]	Loss: 3.627251
Train Epoch: 2 [4480/5000 (89%)]	Loss: 2.901611


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

tensor([206,  81,  60, 300, 103, 193, 361, 163,  69, 120, 213, 133,  85, 318,
        349, 133, 200, 140, 359, 234], device='cuda:0')

Validation set: Average loss: 3.3271, Accuracy: 181/500 (36%)

tensor([200,  55, 342, 359, 100,  48, 331,  81, 107, 119,  99, 213, 338, 136,
        300, 157, 225,   6, 103, 213], device='cuda:0')
/n
tensor([200, 221, 342,   5, 100, 192, 331, 298, 122, 168, 392, 315, 217,  59,
        300, 157, 110,   6, 103, 213], device='cuda:0')
Train Epoch: 3 [0/5000 (0%)]	Loss: 2.290776
Train Epoch: 3 [640/5000 (13%)]	Loss: 1.110156
Train Epoch: 3 [1280/5000 (25%)]	Loss: 1.680406
Train Epoch: 3 [1920/5000 (38%)]	Loss: 1.711351


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 3 [2560/5000 (51%)]	Loss: 1.202946
Train Epoch: 3 [3200/5000 (64%)]	Loss: 1.604950
Train Epoch: 3 [3840/5000 (76%)]	Loss: 1.508544
Train Epoch: 3 [4480/5000 (89%)]	Loss: 1.148366
tensor([227, 376, 245, 242,  87,  41, 293,   2, 326, 227, 297, 219, 206, 163,
         81, 170, 297, 230,  37, 153], device='cuda:0')

Validation set: Average loss: 2.7241, Accuracy: 223/500 (45%)

tensor([126,  48,  95, 230, 163, 297, 387, 245,  81, 307,   6, 120, 373,  37,
        108, 135,  94, 140, 296, 216], device='cuda:0')
/n
tensor([126, 188,  95, 220,  43,  62, 387, 245,  81, 307,   6, 120,  11, 174,
        230, 180, 128, 273,  57, 204], device='cuda:0')
Train Epoch: 4 [0/5000 (0%)]	Loss: 0.555689
Train Epoch: 4 [640/5000 (13%)]	Loss: 0.373845


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 4 [1280/5000 (25%)]	Loss: 0.593408
Train Epoch: 4 [1920/5000 (38%)]	Loss: 0.217324
Train Epoch: 4 [2560/5000 (51%)]	Loss: 0.981889
Train Epoch: 4 [3200/5000 (64%)]	Loss: 0.318997
Train Epoch: 4 [3840/5000 (76%)]	Loss: 0.548430
Train Epoch: 4 [4480/5000 (89%)]	Loss: 0.470439
tensor([211, 384, 314,  48,  48,  48, 370,  46, 338, 246, 221, 268,  86, 227,
         95,  34, 207, 133, 108,  47], device='cuda:0')

Validation set: Average loss: 2.5689, Accuracy: 237/500 (47%)

tensor([336, 143,  48, 370, 227, 376, 133, 216, 213, 326, 213,  46, 251,  46,
        375,   7, 300, 185, 161, 150], device='cuda:0')
/n
tensor([207, 113,  48, 183, 227, 175, 228, 216,  34, 256, 213,  46, 251,  52,
        375,   7, 300, 159, 284,   2], device='cuda:0')
Train Epoch: 5 [0/5000 (0%)]	Loss: 0.127228


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 5 [640/5000 (13%)]	Loss: 0.235108
Train Epoch: 5 [1280/5000 (25%)]	Loss: 0.164435
Train Epoch: 5 [1920/5000 (38%)]	Loss: 0.116940
Train Epoch: 5 [2560/5000 (51%)]	Loss: 0.098189
Train Epoch: 5 [3200/5000 (64%)]	Loss: 0.101489
Train Epoch: 5 [3840/5000 (76%)]	Loss: 0.302964
Train Epoch: 5 [4480/5000 (89%)]	Loss: 0.194840
tensor([184, 331, 274,  92, 227, 300, 393,  92,   8, 245, 263,  81, 249, 251,
        380, 213, 264, 342,  63, 181], device='cuda:0')

Validation set: Average loss: 2.5303, Accuracy: 238/500 (48%)

tensor([ 55, 154,  95, 380, 208, 206, 258,  95, 296,  81,  10, 251, 318, 170,
        118,   2, 349,  48, 133, 200], device='cuda:0')
/n
tensor([137,  56,  95, 227, 208, 113, 223,  95,  57,  81,  10, 251, 318, 170,
        117,  60,  40, 298, 130, 200], device='cuda:0')
Train Epoch: 6 [0/5000 (0%)]	Loss: 0.050154
Train Epoch: 6 [640/5000 (13%)]	Loss: 0.021507
Train Epoch: 6 [1280/5000 (25%)]	Loss: 0.054287


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 6 [1920/5000 (38%)]	Loss: 0.072133
Train Epoch: 6 [2560/5000 (51%)]	Loss: 0.041684
Train Epoch: 6 [3200/5000 (64%)]	Loss: 0.072165
Train Epoch: 6 [3840/5000 (76%)]	Loss: 0.039493
Train Epoch: 6 [4480/5000 (89%)]	Loss: 0.032920
tensor([ 21, 115, 213, 336, 273, 114, 200, 268,  48, 156, 219,  74, 135, 170,
        364, 225, 256, 165,   5, 159], device='cuda:0')

Validation set: Average loss: 2.5547, Accuracy: 232/500 (46%)

tensor([216,   2, 140, 349, 300, 344, 331, 295, 105,  85, 227, 112,  24,  12,
        100, 221,  86, 213, 230, 287], device='cuda:0')
/n
tensor([216,   2, 173,  40, 133,  54, 331, 295, 105,  63,  48, 149,  24,  12,
        100, 374, 377, 213, 113, 308], device='cuda:0')
Train Epoch: 7 [0/5000 (0%)]	Loss: 0.015708
Train Epoch: 7 [640/5000 (13%)]	Loss: 0.045948
Train Epoch: 7 [1280/5000 (25%)]	Loss: 0.037011
Train Epoch: 7 [1920/5000 (38%)]	Loss: 0.021245
Train Epoch: 7 [2560/5000 (51%)]	Loss: 0.016665


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 7 [3200/5000 (64%)]	Loss: 0.023955
Train Epoch: 7 [3840/5000 (76%)]	Loss: 0.023635
Train Epoch: 7 [4480/5000 (89%)]	Loss: 0.038928
tensor([242,  95, 244,  22, 338, 192, 173,  69, 225, 232, 366, 244, 174, 133,
         46,  41, 107, 140, 296, 280], device='cuda:0')

Validation set: Average loss: 2.5336, Accuracy: 232/500 (46%)

tensor([ 47,  76,  47, 221, 225,  95, 225, 383, 180, 213,  63, 213, 293, 370,
        135,  46, 228, 213, 230, 111], device='cuda:0')
/n
tensor([ 47,  34,  47, 221, 225,  95, 382, 385, 180, 213,  11, 100, 293, 183,
        180,  46,  31, 315, 113, 151], device='cuda:0')
Train Epoch: 8 [0/5000 (0%)]	Loss: 0.023625
Train Epoch: 8 [640/5000 (13%)]	Loss: 0.020660
Train Epoch: 8 [1280/5000 (25%)]	Loss: 0.015727
Train Epoch: 8 [1920/5000 (38%)]	Loss: 0.016697
Train Epoch: 8 [2560/5000 (51%)]	Loss: 0.007792
Train Epoch: 8 [3200/5000 (64%)]	Loss: 0.014860
Train Epoch: 8 [3840/5000 (76%)]	Loss: 0.010112
Train Epoch: 8 [4480/5000 (89%)]	Loss: 0.015420


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

tensor([268,  39,  60, 113, 193,  75, 167, 206,  46,  48,  81,  87, 273, 393,
        227, 133,  34, 184, 193, 219], device='cuda:0')

Validation set: Average loss: 2.5814, Accuracy: 243/500 (49%)

tensor([193,  87, 231, 324,  41, 279,  46, 314, 244, 376,  21, 227,  35,  34,
        319, 170, 110,  16, 307,  48], device='cuda:0')
/n
tensor([193,  87,  82, 324, 320, 279,  46,  77, 216, 175, 330, 227,   3,  34,
        338, 170, 110, 220, 307,  93], device='cuda:0')
Train Epoch: 9 [0/5000 (0%)]	Loss: 0.008388
Train Epoch: 9 [640/5000 (13%)]	Loss: 0.017612
Train Epoch: 9 [1280/5000 (25%)]	Loss: 0.015078
Train Epoch: 9 [1920/5000 (38%)]	Loss: 0.012178


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 9 [2560/5000 (51%)]	Loss: 0.014011
Train Epoch: 9 [3200/5000 (64%)]	Loss: 0.015880
Train Epoch: 9 [3840/5000 (76%)]	Loss: 0.009617
Train Epoch: 9 [4480/5000 (89%)]	Loss: 0.012644
tensor([115, 103, 216, 376,  81, 133,  92, 213, 232, 225, 227, 192, 245, 213,
        370,  96, 293, 111, 358,  85], device='cuda:0')

Validation set: Average loss: 2.5677, Accuracy: 245/500 (49%)

tensor([  8,  48, 213, 245, 270, 199, 225,  48, 184, 124, 280, 136, 253, 384,
         47, 227,  60, 193, 170, 110], device='cuda:0')
/n
tensor([  8,  48,  41, 328,  19,  75, 382,  93, 256,  26, 280, 136, 278, 383,
        227,  48,  60, 203, 170, 110], device='cuda:0')
Train Epoch: 10 [0/5000 (0%)]	Loss: 0.006765
Train Epoch: 10 [640/5000 (13%)]	Loss: 0.013535
Train Epoch: 10 [1280/5000 (25%)]	Loss: 0.013876
Train Epoch: 10 [1920/5000 (38%)]	Loss: 0.010377
Train Epoch: 10 [2560/5000 (51%)]	Loss: 0.010870
Train Epoch: 10 [3200/5000 (64%)]	Loss: 0.018206


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1385478 bytes but only got 23143. Skipping tag 513
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 7276331008 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1879769088 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3014066176 bytes but only got 0. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3568893952 bytes but only got 23144. Skipping tag 4
  warnings.warn(
/usr/local/lib/python3.8/dist-pac

Train Epoch: 10 [3840/5000 (76%)]	Loss: 0.008270


/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 541786190 bytes but only got 0. Skipping tag 16576
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2256669952 bytes but only got 0. Skipping tag 17
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 67518482 bytes but only got 0. Skipping tag 7
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 4454482224 bytes but only got 0. Skipping tag 237
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py:767: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2359296 bytes but only got 0. Skipping tag 4096
  warnings.warn(
/usr/local/lib/python3.8/dist-packag

Train Epoch: 10 [4480/5000 (89%)]	Loss: 0.008527
tensor([ 21, 379, 245, 184, 359, 297,  85, 319,  47, 103,  26, 338, 161,  34,
         22, 146, 227, 151, 143,  21], device='cuda:0')

Validation set: Average loss: 2.6374, Accuracy: 236/500 (47%)

tensor([101,   6, 170, 300,  86, 200, 232,  41,  47, 216,  47,  34, 105,   5,
         10, 375,  41, 213, 359, 100], device='cuda:0')
/n
tensor([ 44,   6, 170, 128, 392, 200, 193,  41, 177, 216,  47, 300, 105, 298,
         10, 375, 213, 213,   5, 100], device='cuda:0')


In [ ]:
_, predicted = torch.max(outputs, 1)

print('Predicted: ', ' '.join('%5s' % classes[predicted[j]]
                              for j in range(4)))